### PR TITLE
Fix preventing glightbox to jump on top

### PR DESCRIPTION
**Pull request by ritchiemarkov**
https://github.com/biati-digital/glightbox/issues/22 - Issue

### CODE REVIEW

**Comment by ritchiemarkov** [comment]
🥳 - 1rst pr!

**Review by crftwrk — APPROVED** [review]

**Comment by crftwrk** [comment]
👍

**Comment by ritchiemarkov** [comment]
Ok basti, its works well. now i have to create a version without glightbox.
 reason : this version of plugin costrains only to created gallery. not every image or simple /  not swiper galley.  are you agree ?

**Comment by crftwrk** [comment]
I would like the plugin main branch keep as it is amd improve it from timr to time for basic usage. But of course, you can fork and create different branches. Make as many versions as you want.

**Comment by ritchiemarkov** [comment]
👌

Il gio 6 ott 2022, 21:21 Basti ***@***.***> ha scritto:

**Pull request merged**
